# Generated by Django 3.2.8 on 2021-10-31 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('corporate_name', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('address_complement', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('address_complement', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.IntegerField(choices=[(0, 'Receiver'), (1, 'Donator')], default=0)),
                ('transaction_type', models.IntegerField(choices=[(0, 'Money'), (1, 'Food')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInstance',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usertype')),
            ],
        ),
    ]
